// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSettings():Promise<string>;

export function GetWslList():Promise<string>;

export function SetBackupPath(arg1:string):Promise<void>;

export function SetDefaultTerminal(arg1:number):Promise<void>;

export function TerminateWsl(arg1:string):Promise<void>;
