// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateBackupFile(arg1:string,arg2:string,arg3:number):Promise<void>;

export function GetBackupFiles(arg1:string):Promise<string>;

export function GetSettings():Promise<string>;

export function LaunchDistro(arg1:string):Promise<void>;

export function OpenBackupFolder(arg1:string):Promise<void>;

export function RenameBackupFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RequestShutdownWsl():Promise<boolean>;

export function RestoreDistro(arg1:string,arg2:string):Promise<void>;

export function SelectFolder():Promise<string>;

export function SetSettings(arg1:string):Promise<void>;

export function TerminateWsl(arg1:string):Promise<void>;

export function TestPath(arg1:string):Promise<boolean>;
