// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateBackupFile():Promise<void>;

export function GetSettings():Promise<string>;

export function GetWslList():Promise<string>;

export function LaunchDistro(arg1:number,arg2:string):Promise<void>;

export function SetBackupPath(arg1:string):Promise<void>;

export function TerminateWsl(arg1:string):Promise<void>;
