// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateBackupFile() {
  return window['go']['main']['App']['CreateBackupFile']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetWslList() {
  return window['go']['main']['App']['GetWslList']();
}

export function LaunchDistro(arg1, arg2) {
  return window['go']['main']['App']['LaunchDistro'](arg1, arg2);
}

export function SetBackupPath(arg1) {
  return window['go']['main']['App']['SetBackupPath'](arg1);
}

export function TerminateWsl(arg1) {
  return window['go']['main']['App']['TerminateWsl'](arg1);
}
