// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateBackupFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateBackupFile'](arg1, arg2, arg3);
}

export function GetBackupFiles(arg1) {
  return window['go']['main']['App']['GetBackupFiles'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetWslList() {
  return window['go']['main']['App']['GetWslList']();
}

export function LaunchDistro(arg1) {
  return window['go']['main']['App']['LaunchDistro'](arg1);
}

export function OpenBackupFolder(arg1) {
  return window['go']['main']['App']['OpenBackupFolder'](arg1);
}

export function RenameBackupFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameBackupFile'](arg1, arg2, arg3);
}

export function RestoreDistro(arg1, arg2) {
  return window['go']['main']['App']['RestoreDistro'](arg1, arg2);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SetBackupPath(arg1) {
  return window['go']['main']['App']['SetBackupPath'](arg1);
}

export function ShutdownWsl() {
  return window['go']['main']['App']['ShutdownWsl']();
}

export function TerminateWsl(arg1) {
  return window['go']['main']['App']['TerminateWsl'](arg1);
}
